name: fitplan
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.2+3

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:

  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.6
  realm: ^20.0.0
  shared_preferences: ^2.3.2
  table_calendar: ^3.1.2
  intl: ^0.19.0
  uuid: ^4.5.1
  auto_route: ^9.2.2
  package_info_plus: ^8.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
flutter_intl:
  enabled: true
