name: fitplan
description: "A new Flutter project."
publish_to: 'none'
version: 0.2.3+5

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:

  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.6
  shared_preferences: ^2.5.1
  table_calendar: ^3.1.2
  intl: ^0.19.0
  uuid: ^4.5.1
  auto_route: ^9.2.2
  package_info_plus: ^8.1.0
  drift: ^2.25.0
  sqlite3_flutter_libs: ^0.5.30
  path_provider: ^2.1.5
  path: ^1.9.0 
  duration_picker: ^1.2.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4
  purchases_flutter: ^8.6.0
  purchases_ui_flutter: ^8.6.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.5
  build_runner: ^2.4.14
  drift_dev: ^2.25.1
  intl_utils: ^2.8.10
  

flutter:
  uses-material-design: true
  assets:
    - assets/splash.jpg
    - assets/splashx2.jpg
    - assets/logo.png
flutter_intl:
  enabled: true


flutter_icons:
  android: true
  ios: true
  image_path: "assets/ic_launcher.png"
  remove_alpha_ios: true


flutter_native_splash:
  color: "#FEBE09"  
  color_dark: "#FEBE09" 
  image: assets/logo.png  

  android: true
  ios: true
  fullscreen: true 
  android_12:
    color: "#FEBE09"
    image: assets/logo.png
    icon_background_color: "#FEBE09"
    color_dark: "#FEBE09"
    icon_background_color_dark: "#FEBE09"

  