name: fitplan
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.2+3

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:

  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.5
  realm: ^2.3.0
  shared_preferences: ^2.2.3
  table_calendar: ^3.0.9
  intl: ^0.18.1
  uuid: ^4.4.0
  auto_route: ^8.1.3
  package_info_plus: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
flutter_intl:
  enabled: true
